Paul romanov/button
Anastasiya1982/pointing-poker pull request #10
Opened 2021-09-03 20:20 UTC by PaulRomanov

Создал компоненты button and switch

2021-09-04 17:00 UTC, mallky requested changes

2021-09-04 17:00 UTC, mallky commented on pointer-poker/src/component/btnCancel/BtnCancel.tsx
> +    <div>
Нам не нужен div, у нас просто кнопка, достаточно button

2021-09-04 17:00 UTC, mallky commented on pointer-poker/src/component/btnCancel/BtnCancel.tsx
> +const BtnCancel = () => {
Нам не нужно создавать кучу файлов с разными кнопками, весь смысл реакта и его компонентного подхода тогда теряется
Нам нужно создать ОДИН компонент, в который можно будет передавать разные props, благодаря которым компонент будет работать и отрисовываться по-разному. То есть есть один компонент, который называется Button. Как минимум, он должен иметь следующие props:
1. label - текст, который будет отображаться
2. onClick - функция, которая будет вызываться при клике на кнопку
3. type - тип кнопки, который будет отвечать за стиль кнопки. Например может принимать два значения 'filled' или 'unfilled' - соотвественно либо с темным бекграундом, либо с белым

2021-09-04 17:00 UTC, mallky commented on pointer-poker/src/component/btnCancel/btnCancel.css
> +  text-decoration: none;
обьясни пожалуйста, для чего нам этот стиль тут?

2021-09-05 07:52 UTC, PaulRomanov commented on pointer-poker/src/component/btnCancel/btnCancel.css
> +  text-decoration: none;
4 строка не нужна.

2021-09-05 07:53 UTC, PaulRomanov commented on pointer-poker/src/component/btnCancel/BtnCancel.tsx
> +    <div>
изменю

2021-09-05 11:22 UTC, PaulRomanov commented on pointer-poker/src/component/btnCancel/BtnCancel.tsx
> +const BtnCancel = () => {
изменил

2021-09-05 12:18 UTC, PaulRomanov commented on pointer-poker/src/component/btnCancel/BtnCancel.tsx
> +const BtnCancel = () => {
сделал 1 компонент общей кнопки

2021-09-05 15:14 UTC, mallky requested changes

2021-09-05 15:14 UTC, mallky commented on pointer-poker/src/component/button/Button.tsx
> +// eslint-disable-next-line @typescript-eslint/no-redeclare
в коде не должно быть таких заглушек, иначе смысл линтеров теряется

2021-09-05 15:14 UTC, mallky commented on pointer-poker/src/component/btnSwitch/BtnSwitch.tsx
> +const BtnSwitch = () => {
у компонента нет никаких пропсов, сейчас он выглядит бесполезным, мы не сможем его сразу брать и использовать. У свитчера как минимум должен быть пропс отвечающий за внешний вид: активный или неактивный, и пропс onClick, который вызывается по нажатию

2021-09-05 15:14 UTC, mallky commented on pointer-poker/src/pages/Main/Main.tsx
> -import React from 'react';
Main/Main.scss и Main/Main.tsx не должно быть в пул реквесте, потому что пул реквест их совсем не затрагивает. Это значит что внутри этих файлов не должно быть никаких изменений, по сравнению с веткой develop

2021-09-05 15:14 UTC, mallky commented on pointer-poker/src/component/button/Button.tsx
> +type propTypes = {
лучше типы пропсов задавать через [interface](https://www.typescriptlang.org/docs/handbook/interfaces.html) и писать этот тип до начала обьявления компонента (например на 5 строке). Тип пишется с большой буквы: `interface Props {...}`

2021-09-05 15:14 UTC, mallky commented on pointer-poker/src/component/button/Button.tsx
> +  onClick: () => {},
если в типе функции ты пишешь () => {}, то это значит что функция возвращает обьект, в нашем случае функция ничего не возвращает, лучше написать `onClick: () => void`

2021-09-05 15:14 UTC, mallky commented on pointer-poker/src/component/button/Button.tsx
> +    className
как я понял стилизацию кнопки ты делаешь через передачу дополнительного класса. Это ок, так делать можно, но в нашем конкретно случае есть только два варианта расцветки кнопки, поэтому я предлагал передавать проп type, который может быть 'filled' или 'unfilled' (два текстовых значения). Соотвественно если Button получает type= 'filled', то выставляем класс 'button-fill', иначе выставляем класс для незакрашенной кнопки. Сами классы можно описать в Botton.css, получится что все о кнопке будет в одном месте

2021-09-05 19:59 UTC, PaulRomanov commented on pointer-poker/src/component/button/Button.tsx
> +// eslint-disable-next-line @typescript-eslint/no-redeclare
забыл убрать.

2021-09-05 20:01 UTC, PaulRomanov commented on pointer-poker/src/pages/Main/Main.tsx
> -import React from 'react';
мне казалось я не комитил изменения там

2021-09-05 20:03 UTC, PaulRomanov commented on pointer-poker/src/component/button/Button.tsx
> +type propTypes = {
переделал

2021-09-05 20:04 UTC, PaulRomanov commented on pointer-poker/src/component/button/Button.tsx
> +  onClick: () => {},
изменил

2021-09-05 20:05 UTC, PaulRomanov commented on pointer-poker/src/component/button/Button.tsx
> +    className
Если это очень принципиально, то я в принципе могу попробовать все переделать.

2021-09-05 20:09 UTC, PaulRomanov commented on pointer-poker/src/component/btnSwitch/BtnSwitch.tsx
> +const BtnSwitch = () => {
за внешний вид вроде как там все в css описано.  
props onClick добавил

2021-09-06 18:53 UTC, mallky requested changes

2021-09-06 18:53 UTC, mallky commented on pointer-poker/src/component/btnSwitch/BtnSwitch.tsx
> +const BtnSwitch: FC<Props> = (onClick) => {
в компонент приходят все пропсы, а не один onClick

2021-09-06 18:53 UTC, mallky commented on pointer-poker/src/component/btnSwitch/BtnSwitch.tsx
> +      <input type="checkbox" id="sw" />
onClick нигде не применяется, также не хватает пропса, который убет отвечать за состояние компонента - активное, неактивно. Как пример можно посмотреть тут: https://tech.skbkontur.ru/react-ui/#/Components/Toggle

2021-09-06 18:53 UTC, mallky commented on pointer-poker/src/component/button/Button.tsx
> +type typeBtn = 'filled' | 'unfilled'
типы как и интерфейсы всегда пишутся с большой буквы

2021-09-06 18:53 UTC, mallky commented on pointer-poker/src/component/button/Button.tsx
> +  typeBtn: string,
у нас может быть только два типа кнопок, поэтому тип лучше написать не  `string`, а просто typeBtn: 'filled' | 'unfilled'

2021-09-06 18:53 UTC, mallky commented on pointer-poker/src/component/button/button.scss
> +
Main.scss и Main.tsx не должно быть в пулреквесте. Это значит что нужно их вернуть к тому состоянию, в котором они были, когда ты делал новую ветку от develop. Сейчас они у тебя просто удалены, это приведет к тому, что будет конфликт с веткой develop, соотвественно нельзя будет вмержить ветку

2021-09-07 06:28 UTC, mallky approved these changes

2021-09-07 06:28 UTC, merged