Valeryia miron/feature/avatar plate
Anastasiya1982/pointing-poker pull request #13
Opened 2021-09-04 10:54 UTC by ValeryiaMIRON

- [ ] Avatar (круг с изображением или буквами)
 -[ ] Plate (прямоугольная плашка с тенью)

2021-09-04 17:07 UTC, mallky requested changes

2021-09-04 17:07 UTC, mallky commented on pointer-poker/src/App.tsx
> +      <Plate />
давай пока уберем App.tsx из пул реквеста, чтобы потом ни у кого не было конфликтов при мерже изменений

2021-09-04 17:07 UTC, mallky commented on pointer-poker/src/components/avatar/Avatar.tsx
> +const Avatar = () => {
Сейчас Avatar никак не кастомизируется, но мы уже знаем что на месте аватара может быть либо картинка, либо текст, поэтому ты уже можешь написать, что данный компонент принимает такие props:
1. img - картинка, которую мы показываем
2. fallbackText - текст, который мы показываем, если img отсутсвует

Эти props нужно поставить в соотвествующие места в компоненте

2021-09-04 17:07 UTC, mallky commented on pointer-poker/src/components/avatar/Avatar.tsx
> +      <div className="avatar-info" id="avatar">
у тебя не должно быть двух вложенных дивов, должен быть толкьо один, внутри которого отображается либо картинка, либо текст, причем этот див должен иметь одинаковые стили для обоих случаев

2021-09-04 17:07 UTC, mallky commented on pointer-poker/src/components/plate/Plate.tsx
> +const Plate = () => {
Plate должен принимать children в качестве props и отображать их, если они есть

2021-09-04 17:07 UTC, mallky commented on pointer-poker/src/components/plate/plate.css
> +  width: 500px;
а точно должна быть такая большая ширина и высота?

2021-09-05 11:39 UTC, ValeryiaMIRON commented on pointer-poker/src/App.tsx
> +      <Plate />
Done

2021-09-05 11:39 UTC, ValeryiaMIRON commented on pointer-poker/src/components/avatar/Avatar.tsx
> +const Avatar = () => {
Done

2021-09-05 11:39 UTC, ValeryiaMIRON commented on pointer-poker/src/components/avatar/Avatar.tsx
> +      <div className="avatar-info" id="avatar">
Done

2021-09-05 11:40 UTC, ValeryiaMIRON commented on pointer-poker/src/components/plate/Plate.tsx
> +const Plate = () => {
Done

2021-09-05 11:40 UTC, ValeryiaMIRON commented on pointer-poker/src/components/plate/plate.css
> +  width: 500px;
Done

2021-09-05 14:55 UTC, mallky requested changes

2021-09-05 14:55 UTC, mallky commented on pointer-poker/src/components/avatar/Avatar.tsx
> +type Props = {
давайте задавать тип пропсов через [interface](https://www.typescriptlang.org/docs/handbook/interfaces.html)

2021-09-05 14:55 UTC, mallky commented on pointer-poker/src/components/plate/Plate.tsx
> +type PropsPlate = {
также, давай лучше заменим на interface

2021-09-05 14:55 UTC, mallky commented on pointer-poker/src/components/plate/Plate.tsx
> +  // className: string;
удали пожалуйста комментарий

2021-09-05 14:55 UTC, mallky commented on pointer-poker/src/components/plate/Plate.tsx
> +  // const g = classNames('plate', className);
удали пожалуйста комментарий

2021-09-05 14:55 UTC, mallky commented on pointer-poker/src/components/plate/Plate.tsx
> +  const classDate = classNames('name');
а для чего нам здесь classNames библиотека? мне кажется что она здесь не особо нужна

2021-09-05 14:55 UTC, mallky commented on pointer-poker/src/components/plate/Plate.tsx
> +      <div className={classDate}>{name}</div>
Plate - это просто компонент, внутрь которого можно пихать все что угодно, любой компонент. Сейчас это нечто захардкоженное - тут всегда есть name, job и Avatar, причем аватар с конкретным значением для текста.

Мы сейчас создаем общие компоненты, которые могут принимать определенные значения и отображать их. Внутри этих компонентов не должно быть никакого хардкода.

Вот здесь пример того, что я ожидаю увидеть в Plate комопненте:  https://ru.reactjs.org/docs/composition-vs-inheritance.html

2021-09-05 14:55 UTC, mallky commented on pointer-poker/src/styles.scss
> +
похоже что этот файл не относится к этому пул реквесту, давай его отсюда уберем

2021-09-05 15:25 UTC, ValeryiaMIRON commented on pointer-poker/src/components/avatar/Avatar.tsx
> +type Props = {
done

2021-09-05 15:25 UTC, ValeryiaMIRON commented on pointer-poker/src/components/plate/Plate.tsx
> +type PropsPlate = {
done

2021-09-05 15:25 UTC, ValeryiaMIRON commented on pointer-poker/src/components/plate/Plate.tsx
> +  // className: string;
done

2021-09-05 15:25 UTC, ValeryiaMIRON commented on pointer-poker/src/components/plate/Plate.tsx
> +  // const g = classNames('plate', className);
done

2021-09-05 15:25 UTC, ValeryiaMIRON commented on pointer-poker/src/components/plate/Plate.tsx
> +  const classDate = classNames('name');
done

2021-09-05 15:25 UTC, ValeryiaMIRON commented on pointer-poker/src/components/plate/Plate.tsx
> +      <div className={classDate}>{name}</div>
done

2021-09-05 15:25 UTC, ValeryiaMIRON commented on pointer-poker/src/styles.scss
> +
done

2021-09-05 17:39 UTC, mallky requested changes

2021-09-05 17:39 UTC, mallky commented on pointer-poker/src/styles.scss
> +
файл все еще в пулреквесте)

2021-09-05 17:39 UTC, mallky commented on pointer-poker/package.json
> +    "classnames": "^2.3.1",
нужно убрать, потому что нигде не используется. Также нужно вернуть package-lock к первоначальному виду

2021-09-05 17:39 UTC, mallky commented on pointer-poker/src/components/plate/Plate.tsx
> +  children: string;
у children тип React.ReactNode

2021-09-05 20:10 UTC, ValeryiaMIRON commented on pointer-poker/package.json
> +    "classnames": "^2.3.1",
done

2021-09-05 20:10 UTC, ValeryiaMIRON commented on pointer-poker/src/components/plate/Plate.tsx
> +  children: string;
done

2021-09-06 18:58 UTC, mallky approved these changes

2021-09-06 18:58 UTC, merged