Create input and select
Anastasiya1982/pointing-poker pull request #18
Opened 2021-09-06 07:18 UTC by ValeryiaMIRON

2021-09-06 19:19 UTC, mallky requested changes

2021-09-06 19:19 UTC, mallky commented on pointer-poker/src/components/input/Input.tsx
> +const Input: FC<PropsInput> = ({ className }) => {
input должен быть контролируемым, то есть мы должны уметь по изменению его значения получать данные в реакте. То есть должны быть пропсы `value` и `onChange`. Аналогично для селекта

https://ru.react.js.org/docs/forms.html

Пример дизайна компонента https://tech.skbkontur.ru/react-ui/#/Components/Input

2021-09-06 19:55 UTC, ValeryiaMIRON commented on pointer-poker/src/components/input/Input.tsx
> +const Input: FC<PropsInput> = ({ className }) => {
done

2021-09-07 09:06 UTC, mallky requested changes

2021-09-07 09:06 UTC, mallky commented on pointer-poker/src/components/input/Input.tsx
> +  onChange: () => void;
в onChange должен передаваться аргумент

2021-09-07 09:06 UTC, mallky commented on pointer-poker/src/components/selectModal/SelectModal.tsx
> +  onChange: () => void;
в onChange должен передаваться аргумент

2021-09-07 09:17 UTC, ValeryiaMIRON commented on pointer-poker/src/components/selectModal/SelectModal.tsx
> +  onChange: () => void;
done

2021-09-07 09:18 UTC, mallky approved these changes

2021-09-07 09:18 UTC, merged