Valeryia miron/feature/user reducer
Anastasiya1982/pointing-poker pull request #30
Opened 2021-09-08 15:48 UTC by ValeryiaMIRON

Created userReducer, added types and name of reducer in store, defined typed hooks and installed react-redux, created file gameReducer

2021-09-08 18:23 UTC, mallky requested changes

2021-09-08 18:23 UTC, mallky commented on pointer-poker/src/redux/userReducer.ts
> +export const selectCount = (state: RootState) => state.user;
насколько я понимаю - это селектор для того, чтобы брать данные юзера. Давай лучше селекторы поместим в отдельный файл, чтобы было удобно находить нужный селектор. То есть предлагаю в папке redux создать папку user с двумя файлами: reducer.ts - в котором будет все, кроме 59 строки, и selectors.ts - в котором будут селекторы.

Название селектора нужно поменять)

2021-09-08 18:23 UTC, mallky commented on pointer-poker/src/redux/userReducer.ts
> +  } as UserState,
чтобы. так не писать, можно сделать отдельную константу с типом UserState:

`const initialState: UserState = {
    firstName: '',
    lastName: '',
    jobPosition: '',
    img: '',
    id: '',
    isScrumMaster: false,
    type: 'player',
  }`

и в createSlice уже использовать ее:
`export const userSlice = createSlice({
  name: 'user',
  initialState,
  ...
`

2021-09-08 18:39 UTC, ValeryiaMIRON commented on pointer-poker/src/redux/userReducer.ts
> +export const selectCount = (state: RootState) => state.user;
done

2021-09-08 18:39 UTC, ValeryiaMIRON commented on pointer-poker/src/redux/userReducer.ts
> +  } as UserState,
done

2021-09-09 06:00 UTC, mallky approved these changes

2021-09-09 06:00 UTC, merged